### ISSUE TITLE
Setting up catalog service consumers with `federate.py` fails

### ISSUE THREAD

**Issue by alanking** [irods/irods_testing_environment#153]
Setting up the catalog service providers works fine, but setting up catalog service consumers fails. Observed when using `ubuntu-20.04-postgres-10.12` project:
```python
Error encountered running setup_irods:
Traceback (most recent call last):
  File "/var/lib/irods/scripts/setup_irods.py", line 515, in main
    setup_server(irods_config,
  File "/var/lib/irods/scripts/setup_irods.py", line 148, in setup_server
    test_put(irods_config)
  File "/var/lib/irods/scripts/setup_irods.py", line 180, in test_put
    raise IrodsError('Post-install test failed. Please check your configuration.')
irods.exceptions.IrodsError: Post-install test failed. Please check your configuration.
```

**Comment by alanking** [comment]
Actually, setting up catalog service consumers fails for `stand_it_up.py` as well. I have confirmed that 4.3.0 as released does not have this problem, so something must have moved in our setup that has not been reflected in the testing environment.

This is a blocker for testing for releases.

**Comment by alanking** [comment]
OR. Or. This commit is to blame: 107bd31412f9c00219bf2e1ffbd60dbe6a63d171

Daggumit.

**Comment by alanking** [comment]
Through an Extremely Manual git-bisect, the latest commit that I have confirmed to be working as far as setting up catalog service consumers is https://github.com/irods/irods/commit/cc7dacafe3060609a23612e3b606eb76fdd21aa3

So, it's not https://github.com/irods/irods_testing_environment/commit/107bd31412f9c00219bf2e1ffbd60dbe6a63d171

Phew

**Comment by alanking** [comment]
I have determined that this is an issue in iRODS, not the testing environment. Closing in favor of https://github.com/irods/irods/issues/6931
